---
# tasks file for zposter
- name: Namespace for zposter
  community.kubernetes.k8s:
    state: "{{ zposter_state }}"
    name: "{{ zposter_namespace }}"
    api_version: v1
    kind: Namespace

- name: zposter service
  community.kubernetes.k8s:
    state: "{{ zposter_state }}"
    namespace: "{{ zposter_namespace }}"
    template: "{{ item }}"
  with_items:
    - content.yml.j2
    - web.yml.j2
    - ingress.yml.j2
  tags:
    - zposter
